name: Build IPTV APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run IPTV script
      run: chmod +x iptv.sh && ./iptv.sh
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Verify project structure
      run: |
        cd IPTVApp
        echo "项目文件列表:"
        find . -name "*.gradle" -o -name "*.xml" -o -name "*.java" | sort
        echo "Gradle Wrapper文件:"
        ls -la gradle/wrapper/ || echo "gradle/wrapper目录不存在"
        ls -la gradlew || echo "gradlew文件不存在"
      
    - name: Build with debug info
      run: |
        cd IPTVApp
        ./gradlew assembleDebug --info --no-daemon
      
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: iptv-app
        path: IPTVApp/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-failure-logs
        path: |
          IPTVApp/app/build/reports/
          IPTVApp/build/reports/