name: Build Complete IPTV APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Make IPTV script executable
      run: chmod +x iptv.sh
      
    - name: Generate IPTV Android Project
      run: ./iptv.sh
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build APK with Gradle
      run: |
        cd IPTVApp
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon
      
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: iptv-complete-app
        path: IPTVApp/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload Build Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: |
          IPTVApp/app/build/reports/
          IPTVApp/build/reports/
        retention-days: 7